### ISSUE TITLE
License of art assets?

### ISSUE THREAD

**Issue by poVoq** [PowaBanga/DDaynormandyFPS#5]
When the game was released, did someone specify the license of the art assets?

**Comment by PowaBanga** [comment]
Yes, i think  that the game is protected by a licence. Go on this website to have more and correct informations, or ask on the ddaydev forum please. 
http://www.ddaydev.com
Why do you a su chat? So toi want use them for a new project ?
Sincerely,PowaBanga
Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : poVoq <notifications@github.com> Date : 21/10/17  11:44  (GMT+01:00) À : PowaBanga/DDaynormandyFPS <DDaynormandyFPS@noreply.github.com> Cc : Subscribed <subscribed@noreply.github.com> Objet : [PowaBanga/DDaynormandyFPS] License of art assets? (#5) 
When the game was released, did someone specify the license of the art assets?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PowaBanga/DDaynormandyFPS","title":"PowaBanga/DDaynormandyFPS","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/PowaBanga/DDaynormandyFPS"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"License of art assets? (#5)"}],"action":{"name":"View Issue","url":"https://github.com/PowaBanga/DDaynormandyFPS/issues/5"}}}
